In [1]:
import numpy as np
import time
import sys

In [3]:
a1 = np.array([1,2,3]) #easier usage, takes shorter time
a2 = np.array([3,3,3])
a1 - a2

array([-2, -1,  0])

In [4]:
a = np.array([5,6,9])
a[0]

5

In [5]:
a[1]

6

In [6]:
a = np.array([[1,2], [3, 4], [5, 6]])  #two-dimensional array
a.ndim    #returns dimensions of the array

2

In [7]:
a.itemsize    #returns bytesize properties 

4

In [8]:
a.dtype       #returns type of the variable

dtype('int32')

In [9]:
a.size      #returns the number of elements of the array

6

In [10]:
a.shape     #returns shape of the matrix 

(3, 2)

In [11]:
a = np.array([[1,2], [3,4], [5, 6]], dtype=complex)    #returns complex numbers(contains imaginary units)
a

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j],
       [5.+0.j, 6.+0.j]])

In [12]:
np.zeros((3,4))        #creates an array of zeros with provided dimensions, same for np.ones

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [14]:
l=range(5)
l

range(0, 5)

In [15]:
np.arange(1,5)    #creates the range provided in the brackets

array([1, 2, 3, 4])

In [16]:
np.arange(1,5,2)  #returns the range of the array every two numbers

array([1, 3])

In [17]:
np.linspace(1,5,10)  #returns an array starting 1, ending 5, 10-spaced (linear sequence of numbers)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [19]:
a = np.array([[1,2], [3,4], [5, 6]])
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [20]:
a.reshape(2,3)  #reverses the array according to numbers provided in the brackets 

array([[1, 2, 3],
       [4, 5, 6]])

In [23]:
a.ravel()       #returns new flattened array, DOES NOT ALTER THE ORGINAL ARRAY


array([1, 2, 3, 4, 5, 6])

In [25]:
a.min()       #returns minimal value

1

In [26]:
a.max()       #returns the MAX

6

In [27]:
a.sum()

21

In [28]:
a.sum(axis=0) #axis 0 returns in this case sum for columns

array([ 9, 12])

In [29]:
a.sum(axis=1) #axis 1 returns in this case sum for rows

array([ 3,  7, 11])

In [31]:
np.sqrt(a)   #returns square root of every number in the array 

array([[1.        , 1.41421356],
       [1.73205081, 2.        ],
       [2.23606798, 2.44948974]])

In [32]:
np.std(a)    #returns standard variation

1.707825127659933

In [33]:
a = np.array([[1,2], [3,4]])  
b = np.array([[5,6], [7,8]])
a + b

array([[ 6,  8],
       [10, 12]])

In [34]:
a.dot(b)  #returns dot product(which helps quantifying relationships between vectors)

array([[19, 22],
       [43, 50]])