In [1]:
import numpy as np

In [2]:
n = [6,7,8]
n[0:2]

[6, 7]

In [3]:
n[-1] #prints last element 

8

In [5]:
a = np.array([6,7,8]) #returns same elements as the list
a[0:2]

array([6, 7])

In [6]:
a[-1]

8

In [8]:
a = np.array([[6,7,8], [1,2,3], [9,3,2]])
a

array([[6, 7, 8],
       [1, 2, 3],
       [9, 3, 2]])

In [10]:
a[1,2]

3

In [11]:
a[0:2,2]  #goes through first and second rows(in slicing 2 not included) and returns third element 

array([8, 3])

In [12]:
a[-1]

array([9, 3, 2])

In [13]:
a[-1,0:2] #takes the last row and returns everything till second index

array([9, 3])

In [14]:
a[:,1:3]

array([[7, 8],
       [2, 3],
       [3, 2]])

In [15]:
a = np.array([[6,7,8], [1,2,3], [9,3,2]])
a
for row in a:
    print(row)

[6 7 8]
[1 2 3]
[9 3 2]


In [16]:
for cell in a.flat:  #prints flattened array 
    print(cell)

6
7
8
1
2
3
9
3
2


In [18]:
a = np.arange(6).reshape(3,2) #prints array from 0 to 5 in 3 x 2 dimensions 
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [19]:
b = np.arange(6,12).reshape(3,2)
b

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [20]:
np.vstack((a,b)) #stacking two arrays (tuple arguments)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [21]:
np.hstack((a,b)) #stacking two arrays horizontally (tuple arguments)

array([[ 0,  1,  6,  7],
       [ 2,  3,  8,  9],
       [ 4,  5, 10, 11]])

In [22]:
a = np.arange(30).reshape(2,15)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [23]:
np.hsplit(a,3)

[array([[ 0,  1,  2,  3,  4],
        [15, 16, 17, 18, 19]]),
 array([[ 5,  6,  7,  8,  9],
        [20, 21, 22, 23, 24]]),
 array([[10, 11, 12, 13, 14],
        [25, 26, 27, 28, 29]])]

In [25]:
result = np.hsplit(a, 3) #showing the new arrays individually- horizontal split
result[0]

array([[ 0,  1,  2,  3,  4],
       [15, 16, 17, 18, 19]])

In [26]:
result[1]

array([[ 5,  6,  7,  8,  9],
       [20, 21, 22, 23, 24]])

In [27]:
result[2]

array([[10, 11, 12, 13, 14],
       [25, 26, 27, 28, 29]])

In [28]:
result = np.vsplit(a,2) #showing the new arrays individually- vertical split
result[0]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]])

In [29]:
result[1]

array([[15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [30]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [31]:
b = a > 4  #returns boolean 
b

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [32]:
a[b] #extracting all values greater than 4 from your array

array([ 5,  6,  7,  8,  9, 10, 11])

In [34]:
a[b] = -1 
a

array([[ 0,  1,  2,  3],
       [ 4, -1, -1, -1],
       [-1, -1, -1, -1]])