In [1]:
import numpy as np

In [3]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [5]:
for row in a:
    print(row)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [7]:
for row in a:
    for cell in row:
        print(cell)

0
1
2
3
4
5
6
7
8
9
10
11


In [8]:
for cell in a.flatten():
    print(cell)

0
1
2
3
4
5
6
7
8
9
10
11


In [9]:
for x in np.nditer(a,order='C'): #C-order means iteration starting from left to right, down and again left to right
    print(x)

0
1
2
3
4
5
6
7
8
9
10
11


In [10]:
for x in np.nditer(a,order='F'): #Fortan-order means iteration starting going down and up
    print(x)

0
4
8
1
5
9
2
6
10
3
7
11


In [11]:
for x in np.nditer(a,order='F', flags=['external_loop']): #Fortan order while taking external_loop
    print(x)

[0 4 8]
[1 5 9]
[ 2  6 10]
[ 3  7 11]


In [13]:
for x in np.nditer(a,op_flags=['readwrite']): #returns an array of the square root's of the previous array
    x[...]=x*x
a

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [14]:
b = np.arange(3,15,4).reshape(3,1)
b

array([[ 3],
       [ 7],
       [11]])

In [15]:
for x,y in np.nditer([a,b]): # takes elements of the both arrays and combines it into new array, exmaple: 0 1, 1 3...
    print(x,y)

0 3
1 3
4 3
9 3
16 7
25 7
36 7
49 7
64 11
81 11
100 11
121 11
